                                                          # NumPy Basics
# NumPy, Python programlam diline ait çok boyutlu dizilerle ve matrislerle çalışmamıza yardım eden ileri düzey matematiksel işlemler yapabilceğmiz bir kütüphanedir. Günümüzde özellikle veri bilimi üzerine çalışanlar başta olmak üzere NumPy. python programlayanlar tarafından çok sık kullanılan bir kütüphanedir.

# Dizinler üzerinde matematiksel, cebirsel ve istatiksel operasyonlar uygulamak için kullanılır. Numpy'in diğer kütüphanelere göre üstünlüklerinden birisi de çok boyutlu dizilerle işlem yapabilmemizi sağlayan fonksiyonlara sahip olmasıdır. Çok boyutlu dizileri hatırlayalım. Bunlar 1 boyutlu, 2 boyutlu ve 3 boyutlu dizilerdir.





# NumPy is a library in the Python programming language that helps us work with multidimensional arrays and matrices, allowing us to perform advanced mathematical operations. Nowadays, especially those working on data science, NumPy. Python is a library that is frequently used by programmers.

# It is used to perform mathematical, algebraic and statistical operations on indexes. One of Numpy's advantages over other libraries is that it has functions that allow us to operate with multidimensional arrays. Let's remember multidimensional arrays.These are 1-dimensional, 2-dimensional and 3-dimensional arrays.

In [2]:
# Numpy ve listelerin farkı   (# Difference between numpy and lists)

In [10]:
# list kullanımı (# list usage)

a = [1,5,10]
b = [1,2,3]

# a*b =>hata verir. (# returns an error.)


In [16]:
import numpy as np

In [18]:
a = np.array([1,5,10])
print(a)

[ 1  5 10]


In [20]:
b = np.array([[1,7,20], [5,8,9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [22]:
# dizini boyutunu öğrenmek için ndim kullanırız.
# We use ndim to find out the directory size.

In [24]:
b.ndim

2

In [26]:
a.ndim

1

In [28]:
# 2 satır 3 sütunlu dizimizin boyunu öğrenmek için shape kullanılır.
# Shape is used to find out the size of our 2 row and 3 column array.

In [30]:
b.shape

(2, 3)

In [34]:
a.dtype                  

dtype('int64')

# dtype` (data type) öğesi, `numpy` dizilerinin veri türünü belirtir. Her bir dizi öğesi aynı veri türüne sahiptir ve `dtype`, dizideki verilerin nasıl yorumlanacağını belirtir.
# The `dtype` (data type) element specifies the data type of `numpy` arrays. Each array element has the same data type, and `dtype` specifies how the data in the array will be interpreted.

In [37]:
# ondalıklı sayı tanımlayalım.
# Let's define a decimal number.

In [39]:
x = np.array([1.0,5.4,10.42])
x.dtype

dtype('float64')

In [41]:
# Dizinin belirli bir hücresine erişmek için satır ve sütun numaraları kullanırız.
# We use row and column numbers to access a specific cell of the array.

In [43]:
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [49]:
b[0,2]     #(satır_index, sütun_index)   #(row_index, column_index)

20

In [51]:
b[1,1]

8

In [61]:
# ilk satırdaki ikinci ve üçüncü elemanlara yani 7'ye ve 20'ye erişelim.
# Let's access the second and third elements in the first row, namely 7 and 20.

In [76]:
b[0,1:]           # [sıfırncı sütun, 1 satır dahil ve 1'den sonraki satır]

array([ 7, 20])

In [77]:
b[1,1]= 18         # normalde 1.satır 1.sütun 8 ama biz 18 olsun istedik bu yüzden eşitledik.  
                   #( normally 1st row 1st column is 8 but we wanted it to be 18 so we equalized it.)
b[1,1]

18

In [80]:
b   # 8 yerine 18 oluştu.  (#18 occurred instead of 8.)

array([[ 1,  7, 20],
       [ 5, 18,  9]])

                                        # Otomatik Dizi Oluşturma (# Automatic Sequence Creation)

In [91]:
# Tümü sıfır matris/dizi (# All zero matrix/array)
dizi_s = np.zeros((2,3))   # 2 satır 3 sütunluk tamasıfır olan dizi          (# 2 row 3 column integer array)
dizi_s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
# Tümü aynı değer olan dizi    (# Array with all the same value)
dizi1 = np.full((4,4), 50)
dizi1

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [109]:
# Random dizi oluşturma            (# Create random array)    # Random 0 ile 1 arasında değer oluşturur. (# Random creates a value between 0 and 1.)
dizi2 = np.random.rand(4,3)
dizi2

array([[0.73598732, 0.66534778, 0.04862779],
       [0.3985935 , 0.70794985, 0.48039712],
       [0.20574528, 0.2684614 , 0.48819555],
       [0.49257408, 0.97479109, 0.50718865]])

In [117]:
# Otomatik random int dizi oluşturma                (# Automatic random int array creation)  
dizi3 = np.random.randint(0,100,size=(5,5))
dizi3

array([[87, 34, 41, 93, 49],
       [80,  9, 43, 96, 78],
       [97, 74, 39, 28, 51],
       [34,  2, 37, 66, 22],
       [ 8, 93, 30, 30, 12]])

In [119]:
# Dizi kopyalarken dikkat!!!    (# Be careful when copying strings!!!)

In [125]:
a = np.array([1,2,3])       # 1,2 ve 3 sayıları ile dizi oluşturduk (# We created an array with the numbers 1,2 and 3)
b = a                       # b dizisini a dizisi diye kaydettik. (We saved the sequence b as sequence a.)
b[0] = 90                   # b'nin sıfırıncı indexine 1 yerine 90 dedik. (# We called the zeroth index of b 90 instead of 1.)

print(a)
print(b)

[90  2  3]
[90  2  3]


In [127]:
# Dizilerde Matematiksel İşlemler (# Mathematical Operations on Arrays)

In [129]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [131]:
a + 4

array([5, 6, 7, 8])

In [133]:
a * 2

array([2, 4, 6, 8])

In [135]:
a / 2 

array([0.5, 1. , 1.5, 2. ])

In [137]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [139]:
a ** 2

array([ 1,  4,  9, 16])

In [141]:
# İstatistik (statistics)

In [145]:
dizi4 = np.array([[1,2,3], [4,5,6]])
dizi4

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
np.min(dizi4)

1

In [149]:
np.sum(dizi4)

21

In [151]:
np.max(dizi4)

6

In [153]:
# Dosyadan dizi yükleme                 (# Loading array from file)

In [161]:
filedata = np.genfromtxt("ornek.txt", delimiter=",")       # ornek adosyadaki dizleri yükledik
filedata = filedata.astype("int32")                        # dosyanın tipini integer yaptık
print(filedata) 

[[1 2 3 4 5 6 7]
 [8 9 7 8 9 9 8]
 [3 3 3 5 7 9 0]]


In [163]:
filedata[1,0]           #1.satır 0. sütunu yazdık.

8